name: Build QMK Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install QMK CLI
        run: pip3 install qmk

      - name: Setup QMK
        run: qmk setup -H . --yes

      - name: Build firmware
        run: qmk compile -kb sofle_pico -km koombot
